
const ALL = window.ALL_DATA;
const shards = ALL.shards;
const shardKeys = Object.keys(shards);
const shardTabs = document.getElementById('shardTabs');
const achGrid = document.getElementById('achGrid');
const achTree = document.getElementById('achTree');
const playerNameEl = document.getElementById('playerName');
const xpFill = document.getElementById('xpFill');
const playerLevel = document.getElementById('playerLevel');
const playerXPPercent = document.getElementById('playerXPPercent');
const resetBtn = document.getElementById('resetBtn');
let selectedShard = shardKeys[0];
shardKeys.forEach(k=>{ const btn=document.createElement('div'); btn.className='shard-tab'; btn.textContent=shards[k].name; btn.addEventListener('click', ()=>{ document.querySelectorAll('.shard-tab').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); selectedShard=k; renderAll(); }); shardTabs.appendChild(btn); });
document.querySelectorAll('.shard-tab')[0].classList.add('active');
const mainRadarCtx = document.getElementById('mainRadar').getContext('2d');
const mainRadar = new Chart(mainRadarCtx, { type:'radar', data: { labels:[], datasets:[{ label:'Domains', data:[], fill:true, backgroundColor:'rgba(127,255,0,0.08)', borderColor:'#7fff00' }]}, options:{scales:{r:{min:0,max:100}}, plugins:{legend:{display:false}}} });
const subRadarCtx = document.getElementById('subRadar').getContext('2d');
const subRadar = new Chart(subRadarCtx, { type:'radar', data:{ labels:[], datasets:[{ label:'Subskills', data:[], fill:true, backgroundColor:'rgba(255,215,0,0.08)', borderColor:'#ffd166' }]}, options:{scales:{r:{min:0,max:100}}, plugins:{legend:{display:false}}} });
function levelFromXp(xp){ return Math.min(100, Math.floor((xp||0)/10) + 1); }
function computeDomainLevels(){ const labels=[]; const values=[]; shardKeys.forEach(k=>{ labels.push(shards[k].name); const skills = shards[k].skills; const skillAvgs = Object.values(skills).map(s=>{ const subs = s.subSkills; const avg = Object.values(subs).reduce((a,b)=>a + levelFromXp(b.xp),0) / Object.keys(subs).length; return avg; }); const domainAvg = Math.round(skillAvgs.reduce((a,b)=>a+b,0) / skillAvgs.length); values.push(domainAvg); }); return {labels, values}; }
function computeSubRadar(shardId){ const shard = shards[shardId]; const labels=[]; const values=[]; Object.entries(shard.skills).forEach(([skillName, skill])=>{ labels.push(skillName); const avg = Math.round(Object.values(skill.subSkills).reduce((a,b)=>a+levelFromXp(b.xp),0) / Object.keys(skill.subSkills).length); values.push(avg); }); return {labels, values}; }
function renderMainRadar(){ const rr = computeDomainLevels(); mainRadar.data.labels = rr.labels; mainRadar.data.datasets[0].data = rr.values; mainRadar.update(); }
function renderSubRadar(shardId){ const r = computeSubRadar(shardId); subRadar.data.labels = r.labels; subRadar.data.datasets[0].data = r.values; subRadar.update(); }
function renderAchievementsGrid(shardId){ achGrid.innerHTML=''; const shard = shards[shardId]; let items = []; Object.keys(shard.tiers).forEach(tk=> items = items.concat(shard.tiers[tk].achievements)); items = items.concat(shard.hiddenAchievements); items.slice(0,80).forEach(ach=>{ const card=document.createElement('div'); card.className='ach-card'; const title=document.createElement('div'); title.className='ach-title'; title.textContent=ach.title; const desc=document.createElement('div'); desc.className='ach-desc'; desc.textContent=ach.description; const meta=document.createElement('div'); meta.className='ach-meta'; meta.textContent=ach.points+' pts • '+'★'.repeat(Math.max(1,ach.difficulty)); card.appendChild(title); card.appendChild(desc); card.appendChild(meta); card.title = ach.id + ' • ' + Object.keys(ach.reward.subSkills).slice(0,2).join(', '); const state = JSON.parse(localStorage.getItem('uc_v2_state') || '{}'); if(state[ach.id]) card.classList.add('completed'); card.addEventListener('click', ()=>{ const st = JSON.parse(localStorage.getItem('uc_v2_state') || '{}'); if(st[ach.id]){ applyReward(ach, -1); delete st[ach.id]; card.classList.remove('completed'); } else { applyReward(ach, +1); st[ach.id] = {time:Date.now()}; card.classList.add('completed'); } localStorage.setItem('uc_v2_state', JSON.stringify(st)); renderAll(); }); achGrid.appendChild(card); }); }
function applyReward(ach, mult){ for(const [path, xp] of Object.entries(ach.reward.subSkills)){ const parts = path.split('.'); if(parts.length < 3) continue; const shardId = parts[0]; const skillName = parts[1]; const subName = parts.slice(2).join('.'); const subObj = shards[shardId].skills[skillName].subSkills; if(subObj && subObj[subName] !== undefined){ subObj[subName].xp = Math.max(0, (subObj[subName].xp||0) + Math.round(xp * mult)); } } }
function renderTree(shardId){ achTree.innerHTML=''; const shard = shards[shardId]; const nodes = []; Object.keys(shard.tiers).slice(1,3).forEach(tk=> shard.tiers[tk].achievements.slice(0,6).forEach(a=> nodes.push(a))); const w = achTree.clientWidth || 600; const h = achTree.clientHeight || 260; const svgNS = 'http://www.w3.org/2000/svg'; const svg = document.createElementNS(svgNS, 'svg'); svg.setAttribute('width', '100%'); svg.setAttribute('height', '100%'); const defs = document.createElementNS(svgNS, 'defs'); const marker = document.createElementNS(svgNS, 'marker'); marker.setAttribute('id','arrow'); marker.setAttribute('markerWidth','6'); marker.setAttribute('markerHeight','6'); marker.setAttribute('refX','5'); marker.setAttribute('refY','3'); marker.setAttribute('orient','auto'); const path = document.createElementNS(svgNS, 'path'); path.setAttribute('d','M0,0 L6,3 L0,6 Z'); path.setAttribute('fill','#666'); marker.appendChild(path); defs.appendChild(marker); svg.appendChild(defs); const cols = 4; const rows = Math.ceil(nodes.length / cols); nodes.forEach((n,i)=>{ const col = i % cols; const row = Math.floor(i / cols); const x = (col + 0.5) * (w/cols); const y = 30 + row * (h/rows); const g = document.createElementNS(svgNS, 'g'); const rect = document.createElementNS(svgNS, 'rect'); rect.setAttribute('x', x - 80); rect.setAttribute('y', y - 14); rect.setAttribute('width', 160); rect.setAttribute('height',28); rect.setAttribute('rx',6); rect.setAttribute('fill','#0d0d0d'); rect.setAttribute('stroke','#222'); const text = document.createElementNS(svgNS, 'text'); text.setAttribute('x', x); text.setAttribute('y', y+4); text.setAttribute('text-anchor','middle'); text.setAttribute('font-family','Press Start 2P,monospace'); text.setAttribute('font-size','9'); text.setAttribute('fill','#fff'); text.textContent = n.title.replace(/\s+\w+-\d{3}$/, ''); g.appendChild(rect); g.appendChild(text); svg.appendChild(g); if(i+1 < nodes.length){ const nx = (((i+1) % cols) + 0.5) * (w/cols); const ny = 30 + Math.floor((i+1)/cols) * (h/rows); const line = document.createElementNS(svgNS, 'line'); line.setAttribute('x1', x); line.setAttribute('y1', y+14); line.setAttribute('x2', nx); line.setAttribute('y2', ny-14); line.setAttribute('stroke','#444'); line.setAttribute('marker-end','url(#arrow)'); svg.appendChild(line); } }); achTree.appendChild(svg); }
function updateProfileUI(){ let totalXp=0; let maxXp=0; shardKeys.forEach(k=>{ Object.values(shards[k].skills).forEach(skill=> Object.values(skill.subSkills).forEach(ss=> totalXp += ss.xp)); Object.values(shards[k].skills).forEach(skill=> Object.values(skill.subSkills).forEach(ss=> maxXp += 1000)); }); const percent = Math.round(totalXp / Math.max(1, maxXp) * 100); xpFill.style.width = Math.max(2, Math.min(100, percent)) + '%'; playerXPPercent.textContent = percent + '%'; const level = Math.max(1, Math.floor(percent / 10) + 1); playerLevel.textContent = level; }
function renderAll(){ renderMainRadar(); renderSubRadar(selectedShard); renderAchievementsGrid(selectedShard); renderTree(selectedShard); updateProfileUI(); }
resetBtn.addEventListener('click', ()=>{ if(confirm('Reset progress?')){ localStorage.removeItem('uc_v2_state'); location.reload(); } });
renderAll();
