
const DATA = window.ALL_DATA;
const shards = DATA.shards;
const shardKeys = Object.keys(shards);
const shardFilter = document.getElementById('shardFilter');
shardFilter.innerHTML = '<option value="all">All</option>' + shardKeys.map(k=>`<option value="${k}">${shards[k].name}</option>`).join('');
shardFilter.addEventListener('change', ()=> renderAchievements(shardFilter.value));
const radarRow = document.getElementById('radarRow'); const radarCharts = {};
shardKeys.forEach(key=>{ const card=document.createElement('div');card.className='radar-card'; const title=document.createElement('h3'); title.textContent=shards[key].name; const canvas=document.createElement('canvas'); canvas.id='radar_'+key; canvas.width=200; canvas.height=180; card.appendChild(title); card.appendChild(canvas); radarRow.appendChild(card); const ctx=canvas.getContext('2d'); radarCharts[key]= new Chart(ctx,{type:'radar',data:{labels:[],datasets:[{label:shards[key].name,data:[],fill:true,backgroundColor:'rgba(255,215,0,0.12)',borderColor:'rgba(255,215,0,0.9)'}]},options:{scales:{r:{min:0,max:100}}}}); });
function levelFromXp(xp){ return Math.min(100, Math.floor((xp||0)/10)+1); }
function computeShardRadar(shardId){ const shard=shards[shardId]; const labels=[]; const values=[]; for(const [skillName,skill] of Object.entries(shard.skills)){ labels.push(skillName); const subs=skill.subSkills; const lvls=Object.values(subs).map(s=>levelFromXp(s.xp)); const avg=Math.round(lvls.reduce((a,b)=>a+b,0)/(lvls.length||1)); values.push(avg);} return {labels,values}; }
function renderRadars(){ for(const key of shardKeys){ const r=computeShardRadar(key); const chart=radarCharts[key]; chart.data.labels=r.labels; chart.data.datasets[0].data=r.values; chart.update(); } }
const achGrid=document.getElementById('achGrid'); const template=document.getElementById('ach-template');
let completion = JSON.parse(localStorage.getItem('uc_completion_v1')||'{}');
function saveCompletion(){ localStorage.setItem('uc_completion_v1', JSON.stringify(completion)); }
function renderAchievements(filter='all'){ achGrid.innerHTML=''; for(const shardId of shardKeys){ if(filter!=='all' && filter!==shardId) continue; const shard=shards[shardId]; for(const tierKey of Object.keys(shard.tiers)){ const tier=shard.tiers[tierKey]; for(const ach of tier.achievements){ const node=template.content.cloneNode(true); const card=node.querySelector('.ach-card'); const title=node.querySelector('.title'); const desc=node.querySelector('.desc'); const pts=node.querySelector('.points'); const diff=node.querySelector('.difficulty'); title.textContent=ach.title; desc.textContent=ach.description; pts.textContent=ach.points+' pts'; diff.textContent=' ★'.repeat(Math.max(1, ach.difficulty)); const rewardPreview=Object.entries(ach.reward.subSkills).slice(0,3).map(p=>p[0].split('.').slice(-1)[0]+':'+p[1]).join(', '); card.title=ach.id + ' • ' + rewardPreview; if(completion[ach.id]) card.classList.add('completed'); card.addEventListener('click', ()=>{ const was=!!completion[ach.id]; if(was){ applyReward(ach,-1); delete completion[ach.id]; card.classList.remove('completed'); } else { applyReward(ach,1); completion[ach.id]=true; card.classList.add('completed'); } saveCompletion(); renderRadars(); }); achGrid.appendChild(node); } } } }
function applyReward(ach,mult){ for(const [path,xp] of Object.entries(ach.reward.subSkills)){ const parts=path.split('.'); if(parts.length<3) continue; const shardId=parts[0]; const skillName=parts[1]; const subName=parts.slice(2).join('.'); const subObj=shards[shardId].skills[skillName].subSkills; if(subObj && subObj[subName]!==undefined){ subObj[subName].xp=Math.max(0,(subObj[subName].xp||0)+Math.round(xp*mult)); } else { const keys=Object.keys(subObj); for(const k of keys){ if(k.toLowerCase().endsWith(parts[2].toLowerCase())){ subObj[k].xp=Math.max(0,(subObj[k].xp||0)+Math.round(xp*mult)); break; } } } } }
renderAchievements(); renderRadars();
